### ISSUE TITLE
Issue: The crawler is crawling too slow, look for  solutions to increase performance

### ISSUE THREAD

**Issue by jacqueline-chan** [UTMediaCAT/mediacat-domain-crawler#19]
Needs investigation
some leads:
- kubernetes ?
- double check if something is holding up the async calls in the crawler
- more servers?
- different way of submitting batches/multithreading

**Comment by kstapelfeldt** [comment]
@jacqueline-chan is going into the code to confirm async calls.

The reason why there might have been a memory leak is because apify default was setting too much RAM (60GB when we only had 40GB). Had to manually be set to 30 on prod. This only happens on production. It doesn't happen when running the application locally. Jacqueline to investigate. @RaiyanRahman will also take a look to advise if anything he thinks of. We still have a memory mystery to solve, but should know more after next week.

**Comment by jacqueline-chan** [comment]
We want to know how long one request will take or ten requests will take. Need some benchmarking @amygaoo will code this up for us

**Comment by kstapelfeldt** [comment]
@jacqueline-chan will run Cheerio
@RaiyanRahman will explore how we might manage multiple concurrent puppeteer instances
@amygaoo will also explore how we might manage multiple concurrent puppeteer instances

**Comment by kstapelfeldt** [comment]
@jacqueline-chan got cheerio working but the URLs it's crawling are not the URLs she expects it to crawl, so she is looking into that issue. It is much faster than puppeteer (rendering html only). 
@RaiyanRahman read up how to add new instances of puppeteer and manage them. There are couple of different ways to do it. We are currently using apify sdk which manages puppeteer. However, we can use puppeteer directly and manage it on our own. We need to test this. Also, if the rendering is very slow we can selectively render certain elements. 
@jacqueline-chan will restart application with setting max and min concurrency. Min concurrency should be set to 50.

**Comment by kstapelfeldt** [comment]
@jacqueline-chan restarted with max concurrency but no speed benefit. Nat suggested we should get to the crux of the issue for puppeteer so she is writing tests to determine what is going on.

@jacqueline-chan and @RaiyanRahman did get Cheerio working. As of right now, it's a lot faster. 

Two streams are being pursued: 1 is tests for the Puppeteer crawler, and 2 is using Cheerio. It was running really well but just started.

**Comment by kstapelfeldt** [comment]
@RaiyanRahman & @jacqueline-chan
Two issues remain: too slow, and not getting links back (only single links)
1. hard-code https:// in puppeteer & cheerio and restarting crawl to see if this resolves the problem of bringing back only single links.
2. fold in selective rendering code for puppeteer (after it's complete) (still need to be able to better block video)
3. Look into manually queueing - do we need to modify in order to resolve issue?
Also: Run tests written by @jacqueline-chan on puppeteer/cheerio to test speed and bring back stats

**Comment by jacqueline-chan** [comment]
> 3. Look into manually queueing - do we need to modify in order to resolve issue?
>    Also: Run tests written by @jacqueline-chan on puppeteer/cheerio to test speed and bring back stats

This third part is completed and is now in testing. While discussing with @RaiyanRahman, we determined that solving task #3, will consequently solve the issue that task #1 was meant to fix and therefore task #1 would be redundant.

Manually enqueuing links has caused an issue of where the crawler does stop periodically crawling and needs to be manually restarted after crawling a couple thousand links. Will need to debug some more + fix this bug

**Comment by kstapelfeldt** [comment]
@RaiyanRahman could not make today's meeting.
@jacqueline-chan implemented number three. When manual queuing is implemented, the crawler does not function as it would using self-derived links. There remains an implementation issue. How could we troubleshoot this? Nat suggests two ways forward: 1. contact developers/github repo maintainers/community or 2. determine how to mark the manual queuing so it is identical to the internal queuing process. This is an issue with cheerio. 

Get site you know will fail
Write tests that focus on the queue.

https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

**Comment by jacqueline-chan** [comment]
@RaiyanRahman please join us in debugging the manually enqueuing issue

**Comment by jacqueline-chan** [comment]
Suggestions from Nat:

use the simplest puppeteer crawler to determine fails/edge cases

**Comment by kstapelfeldt** [comment]
@RaiyanRahman  refactored selective loading and tested the solution. Will this work for pop-ups? Check out: https://www.tubantia.nl/ is an example.

**Comment by kstapelfeldt** [comment]
@RaiyanRahman - looking into other extensions that might resolve the issue of pop-ups. Extensions will work with specific websites, but not generally. @Natkeeran advises that we develop a list of 10-15 sites with this problem and assess the problem for these sites: How to identify? How to close? (put into a .csv). Based on this, we can make decisions about how to address in code - are there any features that seem common to all of these sites?

@jacqueline-chan and @RaiyanRahman will split up target links and put into a sheets doc or something similar (and link in this ticket).

**Comment by jacqueline-chan** [comment]
URLs with pop ups:

Jacqueline 

- [ ] https://www.tubantia.nl/
- [ ] 


Raiyan

URLs that exits immediately - problem unknown
- [ ] https://www.baltimoresun.com/

URLS that take a long time to load (but still ultimately crawls)
- [ ] https://www.bernama.com/en/



URL fixes
http://aljazeerah.info/  -> https://aljazeerah.info/ 
http://buffalonews.com/  - > https://buffalonews.com/

**Comment by kstapelfeldt** [comment]
@RaiyanRahman - inconsistent behaviour when trying to close pop-ups (solutions seem to work sometimes but not others) https://derstandard.at/ -  

@jacqueline-chan has to get database up to get this data. But if she can't get it working will have to restart and run for two days.  She did look into one of the links which has a pop-up and it should have been really easy to click away and click accept but for some reason it still cannot find the button to click away. Can't search for name of button. 

###Todo: 

@jacqueline-chan trying to retrieve database from preliminary crawl
@jacqueline-chan and @RaiyanRahman trying to resolve URL issues
@jacqueline-chan and @RaiyanRahman we need a Google Sheet spreadsheet with all the problematic URLs to make collaboration and documentation easier.

**Comment by jacqueline-chan** [comment]
@jacqueline-chan @RaiyanRahman  Some url links that only has one hit, hit much more frequently when it is tested on its own (without any other domain in the queue). Therefore @RaiyanRahman  would like to explore batching as an option for now. and also look into the possibility of using just using Puppeteer/Playwright without apify to give us more control on the queue mechanism

**Comment by kstapelfeldt** [comment]
@jacqueline-chan - yesterday she was able to retrieve the database! She will make a CSV/Google Sheet - copy/ticket
@jacqueline-chan and @RaiyanRahman trying to resolve URL issues - @Natkeeran reviewed a website that @jacqueline-chan was debugging and found that they are deliberately hiding pop-up (to prevent crawling). This will be difficult. @RaiyanRahman found his site to be very inconsistent. 50% of the time a button could not be found.

@RaiyanRahman suggests we try running batches of websites to see if this improves behaviour. @jacqueline-chan will try running small batches manually to start to see if this makes a difference prior to any code development. If this works, write code. If this doesn't work, don't use apify and write own queuing mechanism.

**Comment by jacqueline-chan** [comment]
CSV for the database. How I determine that a link is most likely a pop up issue is if it starts with https and only has a few hits

go to this site and click on download csv

http://199.241.167.146/

**Comment by kstapelfeldt** [comment]
Imported on the sheet here: https://docs.google.com/spreadsheets/d/1DJfiLT7XGL0XXttp8q0BKRZkn6swWAQ74gdlcaYG3CI/edit#gid=241833616

**Comment by kstapelfeldt** [comment]
@RaiyanRahman trying to automate batching in apify
@jacqueline-chan to:
1. look and see if there are other manual queues already written that we might use (to swap out apify) 
2. send notification if apify crashes (find code and push)
3. Output list of problematic sites. We need some way to spit out a file of URLs that don't get crawled, as we're going to have some in the end.

**Comment by kstapelfeldt** [comment]
@RaiyanRahman did work in batching system for puppeteer using apify, but needs to mark batches at done. He starts by splitting the scope into smaller batches and runs them in succession. Once one is done, he begins the next. He has more than 15 hours left and believes this can be done in that time. 

Overall, we believe that we should explore running multiple instances on separate VMs concurrently, including Raiyan's improvements to the batching process.

@jacqueline-chan to find the documentation, update,  and pass it to @kstapelfeldt for the new co-op student.
@jacqueline-chan to contact compute-canada about imaging existing machines to replicate them, which is currently not working (CC Alejandro and Kirsta)
@jacqueline-chan and @RaiyanRahman to have a meeting and merge everything possible to master. prune branches, please.

**Comment by kstapelfeldt** [comment]
@RaiyanRahman is seeking an optimized point for batches and page crawls per batch. Priority is an exhaustive crawl of individual domains if at all possible. 

@jacqueline-chan been pruning branches and working on compute canada instances and documentation (tasks above)

**Comment by kstapelfeldt** [comment]
@RaiyanRahman  - Looping through domains individually is the best approach. @todo - Making the crawl more robust for subsequent crawls. Raiyan has found a sample implementation in documentation that he is working on.

**Comment by kstapelfeldt** [comment]
Strategy for finding out more:

1. Re-run crawl with only working domains to see if infinite loop problem persists.
2. Install two more versions of the code base, both using only single problematic domains and see what happens.

**Comment by kstapelfeldt** [comment]
1. Re-run crawl with only working domains to see if infinite loop problem persists.
2. Install two more versions of the code base
3. Run one new machine with a single problematic URL
4. Run the second new machine using a new suite of URLs from the scope, and record what works and what is problematic
ran the whole scope. 

Equal importance was given to working domains. Most domains didn't work because of a memory issue - call stack gets too big and takes things down. Tested alongside a local instance. The behaviour was actually the same. NY times was tested on a separate machine. 

In 48 hours:

* 40,421 Crawled Links
* 9,507 JSON
* 14 URLs a minute

Next steps: 

* Revise hash formula to guarantee unique IDS so that JSON is not overwritten

**Comment by kstapelfeldt** [comment]
- Raiyan implemented a different naming convention (UUID and millisecond timestamp). Pushed changes and updated Graham cloud. Seems to be better but still a misfit between # of JSON being produced and number of links crawled. Logs show when it happens, but still figuring out how to avoid issue. 
- Next step: Keep working to find out when infinite loop thing happens: monitor crawl? - Raiyan has a couple of ideas.

**Comment by kstapelfeldt** [comment]
Compute Canada: There are lots of folders hidden with space associated with them. We should check these folders before setting up an instance.

12000 after 24 hours. 8.5 links per minute and faster (15 links per minute) when there is no issue. 
Did some refactoring per Nat's suggestion. 
Crawls to 24 hour mark and then has trouble opening new pages in browser. After 24 hours it happens frequently.
Added timestamps and that made debug file a lot easier. 
If we prevent new page timeout issue, this will speed up a lot and take care of a lot of our issues. 
Stealth crawler might cause problems.
JSON files are now all being created!! - script counts all pages crawled and it matches. 

- Experiment to see what puppeteer configuration flag might be causing the new page timeout issue.
- Consider stopping and restarting crawl with a separate script scheduled to fire when the issue of new page timeout appears.
